# Machine Learning Zoomcamp 2024
## Homework 1: Introduction to Machine Learning
### Name: HOANG LONG TRAN
http://mlzoomcamp.com/

In [2]:
# Set up the environment
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Checking Pandas version

pd.__version__


'2.2.2'

In [5]:
# Download the csv file from the url and save as laptops.csv

!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-10-01 19:44:54--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv.1’

laptops.csv.1       100%[===================>] 291.58K  --.-KB/s    in 0.005s  

2024-10-01 19:44:54 (55.0 MB/s) - ‘laptops.csv.1’ saved [298573/298573]



In [8]:
# Read the csv file and create a datafram

laptopdf = pd.read_csv('laptops.csv')

In [56]:
# Check the Data Frame

laptopdf.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [28]:
# Q2. How many records are in the dataset

laptopdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [58]:
# Q3. How many laptop brands are presented in the dataset?

print(f" Here are the laptop brand {laptopdf['Brand'].unique()} \n")

print(f" Number of laptop brand {len(laptopdf['Brand'].unique())}")

 Here are the laptop brand ['Asus' 'Alurin' 'MSI' 'HP' 'Lenovo' 'Medion' 'Acer' 'Apple' 'Razer'
 'Gigabyte' 'Dell' 'LG' 'Samsung' 'PcCom' 'Microsoft' 'Primux' 'Prixton'
 'Dynabook Toshiba' 'Thomson' 'Denver' 'Deep Gaming' 'Vant' 'Innjoo'
 'Jetwing' 'Millenium' 'Realme' 'Toshiba'] 

 Number of laptop brand 27


In [47]:
# Q4. How many columns in the dataset have missing values?

print(f"Columns have missing value: {laptopdf.isnull().sum()} \n")

print(f"Number of column has missing value: {(laptopdf.isnull().sum() > 0).sum()}")

Columns have missing value: Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64 

Number of column has missing value: 3


In [50]:
# Q5. What is the maximum final price of Dell notebooks in the dataset?

laptopdf[laptopdf['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [68]:
# Q6. Median value of the Screen

# Find the median value of Screen column in the dataset.
print (f"Median value of Screen: {laptopdf['Screen'].median()} \n")

# Next, calculate the most frequent value of the same Screen column.
print (f"Most frequent value of Screen: {laptopdf['Screen'].mode()[0]} \n")

# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
laptopdf['Screen'].fillna(laptopdf['Screen'].mode()[0])

# Now, calculate the median value of the Screen column again.
print (f"Median value of Screen after fillna: {laptopdf['Screen'].median()}")



Median value of Screen: 15.6 

Most frequent value of Screen: 15.6 

Median value of Screen after fillna: 15.6


In [88]:
# Q7. Sum of weights

# Select all the "Innjoo" laptops from the dataset.
laptopdf[laptopdf['Brand'] == 'Innjoo']

# Select only columns RAM, Storage, Screen.
laptopdf[laptopdf['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

# Get the underlying NumPy array. Let's call it X.
X = laptopdf[laptopdf['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']].values
print(X)
print("\n")

# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)
print(XTX)
print("\n")

# Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)
print("\n")

# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])
print (y)
print("\n")

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T).dot(y)
print(w)
print("\n")

# What's the sum of all the elements of the result?
sum_w = w.sum()
print(f"Sum of all the elements of the result: {sum_w}")

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


[1100 1300  800  900 1000 1100]


[45.58076606  0.42783519 45.29127938]


Sum of all the elements of the result: 91.2998806299555
